from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import pandas as pd
import numpy as np
import joblib
import os
from google import genai
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware

# ==========================================
# 1. API & GEMINI SETUP
# ==========================================
# Load the hidden .env file automatically
load_dotenv()

app = FastAPI(title="EventLK AI Planner API")

# --- BLOCK TO FIX FRONTEND ERRORS ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows any frontend to connect. 
    allow_credentials=True,
    allow_methods=["*"],  # Allows POST, GET, OPTIONS, etc.
    allow_headers=["*"],
)

# In production, set this in your environment variables (.env or Render settings)
# For local testing, you can temporarily do: os.environ["GEMINI_API_KEY"] = "your_key"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise RuntimeError("GEMINI_API_KEY environment variable is missing.")

client = genai.Client(api_key=GEMINI_API_KEY)
MODEL_ID = "gemini-2.5-flash-lite"

# ==========================================
# 2. LOAD TRAINED ML MODELS
# ==========================================
# These must be generated by your train.py script first!
try:
    rf_venue = joblib.load('rf_venue_model.pkl')
    rf_alloc = joblib.load('rf_alloc_model.pkl')
    encoder = joblib.load('category_encoder.pkl')
    alloc_cols = joblib.load('alloc_cols.pkl')
    print("✅ ML Models loaded successfully!")
except FileNotFoundError:
    print("⚠️ WARNING: .pkl model files not found. Please run train.py first.")
    rf_venue, rf_alloc, encoder, alloc_cols = None, None, None, None

# ==========================================
# 3. REQUEST & RESPONSE DATA MODELS
# ==========================================
class EventRequest(BaseModel):
    headcount: int
    budget: float
    event_type_display: str  # e.g., "Workshop / Training"
    venue_pref_display: str  # e.g., "Coworking Space"

class EventResponse(BaseModel):
    recommended_venue: str
    total_budget: float
    cost_per_head: float
    budget_allocation: dict
    color_theme: str
    pre_event_plan: str

# ==========================================
# 4. GEMINI FUNCTIONS (From your Streamlit code)
# ==========================================
def generate_color_theme(event_type: str, headcount: int, budget: float) -> str:
    prompt = f"""
    You are a professional event branding expert.

    Suggest a modern and visually appealing color theme for:
    Event Type: {event_type}
    Headcount: {headcount}
    Budget: LKR {budget}

    Return:
    - Theme Name
    - Primary Color (HEX)
    - Secondary Color (HEX)
    - Accent Color (HEX)
    - 2 sentence explanation
    """
    try:
        response = client.models.generate_content(model=MODEL_ID, contents=prompt)
        return response.text
    except Exception as e:
        return f"⚠️ Theme generation failed: {str(e)}"

def generate_pre_event_plan(event_type: str, headcount: int, budget: float) -> str:
    prompt = f"""
    You are an experienced event planning consultant.

    Create a practical pre-event action plan for:
    Event Type: {event_type}
    Expected Headcount: {headcount}
    Budget: LKR {budget}

    The plan should:
    - Be realistic for the scale
    - Consider budget level
    - Include 6–8 clear action steps
    - Be ordered logically
    - Be concise and professional

    Format as a numbered list.
    """
    try:
        response = client.models.generate_content(model=MODEL_ID, contents=prompt)
        return response.text
    except Exception as e:
        return f"⚠️ Planning generation failed: {str(e)}"

# ==========================================
# 5. THE MAIN API ENDPOINT
# ==========================================
@app.post("/api/generate-plan", response_model=EventResponse)
async def generate_plan(request: EventRequest):
    if rf_venue is None:
        raise HTTPException(status_code=500, detail="ML Models are not loaded. Run train.py first.")

    # --- A. ML Feature Mapping (From your Streamlit code) ---
    type_map = {
        "Workshop / Training": ("aiworkshop", "workshopstraining"),
        "Hackathon": ("codehack", "competitionshackathons"),
        "Meetup": ("devmeetup", "meetupscommunity"),
        "Conference": ("techconf", "conferencesexpos"),
        "Panel Discussion": ("aipanel", "talkspanels"),
        "Networking": ("networknight", "careernetworking")
    }

    venue_map = {
        "Any": "auditorium",
        "Auditorium": "auditorium",
        "Coworking Space": "coworkingspace",
        "Exhibition Hall": "exhibitionhall",
        "Studio": "studio",
        "Open Space": "openspace"
    }

    # Safely get mapped values (fallback to defaults if frontend sends weird data)
    e_type, e_cat = type_map.get(request.event_type_display, ("aiworkshop", "workshopstraining"))
    v_cat = venue_map.get(request.venue_pref_display, "auditorium")
    bph = request.budget / request.headcount

    # --- B. ML Prediction Data Prep ---
    input_nums = np.array([[request.headcount, request.budget, bph]])
    input_cats = pd.DataFrame(
        [[e_type, e_cat, v_cat]],
        columns=['eventtype', 'eventcategory', 'venuecategory']
    )

    input_encoded = encoder.transform(input_cats)
    final_input = np.hstack([input_nums, input_encoded])

    # --- C. Execute ML Predictions ---
    venue_pred = rf_venue.predict(final_input)[0]
    alloc_pred = rf_alloc.predict(final_input)[0]

    # --- D. Format Budget Breakdown (From your Streamlit loop) ---
    budget_breakdown = {}
    for i, val in enumerate(alloc_pred):
        name = alloc_cols[i].replace('alloc_', '').title()
        amount = (val / 100) * request.budget
        if amount > 0:
            budget_breakdown[name] = round(amount, 2)

    # --- E. Execute Gemini LLM Generation ---
    theme_text = generate_color_theme(request.event_type_display, request.headcount, request.budget)
    plan_text = generate_pre_event_plan(request.event_type_display, request.headcount, request.budget)

    # --- F. Return JSON to Frontend ---
    return EventResponse(
        recommended_venue=venue_pred,
        total_budget=request.budget,
        cost_per_head=round(bph, 2),
        budget_allocation=budget_breakdown,
        color_theme=theme_text,
        pre_event_plan=plan_text
    )
